// export const countries = [
//   { name: "Afghanistan", code: "AF", timezone: "UTC+04:30" },
//   { name: "Aland Islands", code: "AX", timezone: "UTC+03:00" },
//   { name: "Albania", code: "AL", timezone: "UTC+01:00" },
//   { name: "Algeria", code: "DZ", timezone: "UTC+01:00" },
//   { name: "American Samoa", code: "AS", timezone: "UTC-11:00" },
//   { name: "AndorrA", code: "AD", timezone: "UTC+01:00" },
//   { name: "Angola", code: "AO", timezone: "UTC+01:00" },
//   { name: "Anguilla", code: "AI", timezone: "UTC-04:00" },
//   { name: "Antarctica", code: "AQ", timezone: "UTC+12:00" },
//   { name: "Antigua and Barbuda", code: "AG", timezone: "UTC-04:00" },
//   { name: "Argentina", code: "AR", timezone: "UTC-03:00" },
//   { name: "Armenia", code: "AM", timezone: "UTC+04:00" },
//   { name: "Aruba", code: "AW", timezone: "UTC-04:00" },
//   { name: "Australia", code: "AU", timezone: "UTC+10:00" },
//   { name: "Austria", code: "AT", timezone: "UTC+01:00" },
//   { name: "Azerbaijan", code: "AZ", timezone: "UTC+04:00" },
//   { name: "Bahamas", code: "BS", timezone: "UTC-05:00" },
//   { name: "Bahrain", code: "BH", timezone: "UTC+03:00" },
//   { name: "Bangladesh", code: "BD", timezone: "UTC+06:00" },
//   { name: "Barbados", code: "BB", timezone: "UTC-04:00" },
//   { name: "Belarus", code: "BY", timezone: "UTC+03:00" },
//   { name: "Belgium", code: "BE", timezone: "UTC+01:00" },
//   { name: "Belize", code: "BZ", timezone: "UTC-06:00" },
//   { name: "Benin", code: "BJ", timezone: "UTC+01:00" },
//   { name: "Bermuda", code: "BM", timezone: "UTC-04:00" },
//   { name: "Bhutan", code: "BT", timezone: "UTC+06:00" },
//   { name: "Bolivia", code: "BO", timezone: "UTC-04:00" },
//   { name: "Bosnia and Herzegovina", code: "BA", timezone: "UTC+01:00" },
//   { name: "Botswana", code: "BW", timezone: "UTC+02:00" },
//   { name: "Bouvet Island", code: "BV", timezone: "UTC+01:00" },
//   { name: "Brazil", code: "BR", timezone: "UTC-03:00" },
//   { name: "British Indian Ocean Territory", code: "IO", timezone: "UTC+06:00" },
//   { name: "Brunei Darussalam", code: "BN", timezone: "UTC+08:00" },
//   { name: "Bulgaria", code: "BG", timezone: "UTC+02:00" },
//   { name: "Burkina Faso", code: "BF", timezone: "UTC+00:00" },
//   { name: "Burundi", code: "BI", timezone: "UTC+02:00" },
//   { name: "Cambodia", code: "KH", timezone: "UTC+07:00" },
//   { name: "Cameroon", code: "CM", timezone: "UTC+01:00" },
//   { name: "Canada", code: "CA", timezone: "UTC-05:00" },
//   { name: "Cape Verde", code: "CV", timezone: "UTC-01:00" },
//   { name: "Cayman Islands", code: "KY", timezone: "UTC-05:00" },
//   { name: "Central African Republic", code: "CF", timezone: "UTC+01:00" },
//   { name: "Chad", code: "TD", timezone: "UTC+01:00" },
//   { name: "Chile", code: "CL", timezone: "UTC-03:00" },
//   { name: "China", code: "CN", timezone: "UTC+08:00" },
//   { name: "Christmas Island", code: "CX", timezone: "UTC+07:00" },
//   { name: "Cocos (Keeling) Islands", code: "CC", timezone: "UTC+06:30" },
//   { name: "Colombia", code: "CO", timezone: "UTC-05:00" },
//   { name: "Comoros", code: "KM", timezone: "UTC+03:00" },
//   { name: "Congo", code: "CG", timezone: "UTC+01:00" },
//   {
//     name: "Congo, The Democratic Republic of the",
//     code: "CD",
//     timezone: "UTC+01:00",
//   },
//   { name: "Cook Islands", code: "CK", timezone: "UTC-10:00" },
//   { name: "Costa Rica", code: "CR", timezone: "UTC-06:00" },
//   { name: "Cote D'Ivoire", code: "CI", timezone: "UTC+00:00" },
//   { name: "Croatia", code: "HR", timezone: "UTC+01:00" },
//   { name: "Cuba", code: "CU", timezone: "UTC-05:00" },
//   { name: "Cyprus", code: "CY", timezone: "UTC+02:00" },
//   { name: "Czech Republic", code: "CZ", timezone: "UTC+01:00" },
//   { name: "Denmark", code: "DK", timezone: "UTC+01:00" },
//   { name: "Djibouti", code: "DJ", timezone: "UTC+03:00" },
//   { name: "Dominica", code: "DM", timezone: "UTC-04:00" },
//   { name: "Dominican Republic", code: "DO", timezone: "UTC-04:00" },
//   { name: "Ecuador", code: "EC", timezone: "UTC-05:00" },
//   { name: "Egypt", code: "EG", timezone: "UTC+02:00" },
//   { name: "El Salvador", code: "SV", timezone: "UTC-06:00" },
//   { name: "Equatorial Guinea", code: "GQ", timezone: "UTC+01:00" },
//   { name: "Eritrea", code: "ER", timezone: "UTC+03:00" },
//   { name: "Estonia", code: "EE", timezone: "UTC+02:00" },
//   { name: "Ethiopia", code: "ET", timezone: "UTC+03:00" },
//   { name: "Falkland Islands (Malvinas)", code: "FK", timezone: "UTC-03:00" },
//   { name: "Faroe Islands", code: "FO", timezone: "UTC+00:00" },
//   { name: "Fiji", code: "FJ", timezone: "UTC+12:00" },
//   { name: "Finland", code: "FI", timezone: "UTC+02:00" },
//   { name: "France", code: "FR", timezone: "UTC+01:00" },
//   { name: "French Guiana", code: "GF", timezone: "UTC-03:00" },
//   { name: "French Polynesia", code: "PF", timezone: "UTC-10:00" },
//   { name: "French Southern Territories", code: "TF", timezone: "UTC+05:00" },
//   { name: "Gabon", code: "GA", timezone: "UTC+01:00" },
//   { name: "Gambia", code: "GM", timezone: "UTC+00:00" },
//   { name: "Georgia", code: "GE", timezone: "UTC+04:00" },
//   { name: "Germany", code: "DE", timezone: "UTC+01:00" },
//   { name: "Ghana", code: "GH", timezone: "UTC+00:00" },
//   { name: "Gibraltar", code: "GI", timezone: "UTC+01:00" },
//   { name: "Greece", code: "GR", timezone: "UTC+02:00" },
//   { name: "Greenland", code: "GL", timezone: "UTC-03:00" },
//   { name: "Grenada", code: "GD", timezone: "UTC-04:00" },
//   { name: "Guadeloupe", code: "GP", timezone: "UTC-04:00" },
//   { name: "Guam", code: "GU", timezone: "UTC+10:00" },
//   { name: "Guatemala", code: "GT", timezone: "UTC-06:00" },
//   { name: "Guernsey", code: "GG", timezone: "UTC+00:00" },
//   { name: "Guinea", code: "GN", timezone: "UTC+00:00" },
//   { name: "Guinea-Bissau", code: "GW", timezone: "UTC+00:00" },
//   { name: "Guyana", code: "GY", timezone: "UTC-04:00" },
//   { name: "Haiti", code: "HT", timezone: "UTC-05:00" },
//   {
//     name: "Heard Island and Mcdonald Islands",
//     code: "HM",
//     timezone: "UTC+05:00",
//   },
//   { name: "Holy See (Vatican City State)", code: "VA", timezone: "UTC+01:00" },
//   { name: "Honduras", code: "HN", timezone: "UTC-06:00" },
//   { name: "Hong Kong", code: "HK", timezone: "UTC+08:00" },
//   { name: "Hungary", code: "HU", timezone: "UTC+01:00" },
//   { name: "Iceland", code: "IS", timezone: "UTC+00:00" },
//   { name: "India", code: "IN", timezone: "UTC+05:30" },
//   { name: "Indonesia", code: "ID", timezone: "UTC+07:00" },
//   { name: "Iran", code: "IR", timezone: "UTC+03:30" },
//   { name: "Iraq", code: "IQ", timezone: "UTC+03:00" },
//   { name: "Ireland", code: "IE", timezone: "UTC+00:00" },
//   { name: "Isle of Man", code: "IM", timezone: "UTC+00:00" },
//   { name: "Israel", code: "IL", timezone: "UTC+02:00" },
//   { name: "Italy", code: "IT", timezone: "UTC+01:00" },
//   { name: "Jamaica", code: "JM", timezone: "UTC-05:00" },
//   { name: "Japan", code: "JP", timezone: "UTC+09:00" },
//   { name: "Jersey", code: "JE", timezone: "UTC+00:00" },
//   { name: "Jordan", code: "JO", timezone: "UTC+02:00" },
//   { name: "Kazakhstan", code: "KZ", timezone: "UTC+06:00" },
//   { name: "Kenya", code: "KE", timezone: "UTC+03:00" },
//   { name: "Kiribati", code: "KI", timezone: "UTC+14:00" },
//   {
//     name: "Korea, Democratic People'S Republic of",
//     code: "KP",
//     timezone: "UTC+09:00",
//   },
//   { name: "Korea, Republic of", code: "KR", timezone: "UTC+09:00" },
//   { name: "Kuwait", code: "KW", timezone: "UTC+03:00" },
//   { name: "Kyrgyzstan", code: "KG", timezone: "UTC+06:00" },
//   {
//     name: "Lao People'S Democratic Republic",
//     code: "LA",
//     timezone: "UTC+07:00",
//   },
//   { name: "Latvia", code: "LV", timezone: "UTC+02:00" },
//   { name: "Lebanon", code: "LB", timezone: "UTC+02:00" },
//   { name: "Lesotho", code: "LS", timezone: "UTC+02:00" },
//   { name: "Liberia", code: "LR", timezone: "UTC+00:00" },
//   { name: "Libyan Arab Jamahiriya", code: "LY", timezone: "UTC+02:00" },
//   { name: "Liechtenstein", code: "LI", timezone: "UTC+01:00" },
//   { name: "Lithuania", code: "LT", timezone: "UTC+02:00" },
//   { name: "Luxembourg", code: "LU", timezone: "UTC+01:00" },
//   { name: "Macao", code: "MO", timezone: "UTC+08:00" },
//   {
//     name: "Macedonia, The Former Yugoslav Republic of",
//     code: "MK",
//     timezone: "UTC+01:00",
//   },
//   { name: "Madagascar", code: "MG", timezone: "UTC+03:00" },
//   { name: "Malawi", code: "MW", timezone: "UTC+02:00" },
//   { name: "Malaysia", code: "MY", timezone: "UTC+08:00" },
//   { name: "Maldives", code: "MV", timezone: "UTC+05:00" },
//   { name: "Mali", code: "ML", timezone: "UTC+00:00" },
//   { name: "Malta", code: "MT", timezone: "UTC+01:00" },
//   { name: "Marshall Islands", code: "MH", timezone: "UTC+12:00" },
//   { name: "Martinique", code: "MQ", timezone: "UTC-04:00" },
//   { name: "Mauritania", code: "MR", timezone: "UTC+00:00" },
//   { name: "Mauritius", code: "MU", timezone: "UTC+04:00" },
//   { name: "Mayotte", code: "YT", timezone: "UTC+03:00" },
//   { name: "Mexico", code: "MX", timezone: "UTC-06:00" },
//   {
//     name: "Micronesia, Federated States of",
//     code: "FM",
//     timezone: "UTC+11:00",
//   },
//   { name: "Moldova, Republic of", code: "MD", timezone: "UTC+02:00" },
//   { name: "Monaco", code: "MC", timezone: "UTC+01:00" },
//   { name: "Mongolia", code: "MN", timezone: "UTC+08:00" },
//   { name: "Montenegro", code: "ME", timezone: "UTC+01:00" },
//   { name: "Montserrat", code: "MS", timezone: "UTC-04:00" },
//   { name: "Morocco", code: "MA", timezone: "UTC+00:00" },
//   { name: "Mozambique", code: "MZ", timezone: "UTC+02:00" },
//   { name: "Myanmar", code: "MM", timezone: "UTC+06:30" },
//   { name: "Namibia", code: "NA", timezone: "UTC+02:00" },
//   { name: "Nauru", code: "NR", timezone: "UTC+12:00" },
//   { name: "Nepal", code: "NP", timezone: "UTC+05:45" },
//   { name: "Netherlands", code: "NL", timezone: "UTC+01:00" },
//   { name: "Netherlands Antilles", code: "AN", timezone: "UTC-04:00" },
//   { name: "New Caledonia", code: "NC", timezone: "UTC+11:00" },
//   { name: "New Zealand", code: "NZ", timezone: "UTC+12:00" },
//   { name: "Nicaragua", code: "NI", timezone: "UTC-06:00" },
//   { name: "Niger", code: "NE", timezone: "UTC+01:00" },
//   { name: "Nigeria", code: "NG", timezone: "UTC+01:00" },
//   { name: "Niue", code: "NU", timezone: "UTC-11:00" },
//   { name: "Norfolk Island", code: "NF", timezone: "UTC+11:00" },
//   { name: "Northern Mariana Islands", code: "MP", timezone: "UTC+10:00" },
//   { name: "Norway", code: "NO", timezone: "UTC+01:00" },
//   { name: "Oman", code: "OM", timezone: "UTC+04:00" },
//   { name: "Pakistan", code: "PK", timezone: "UTC+05:00" },
//   { name: "Palau", code: "PW", timezone: "UTC+09:00" },
//   {
//     name: "Palestinian Territory, Occupied",
//     code: "PS",
//     timezone: "UTC+02:00",
//   },
//   { name: "Panama", code: "PA", timezone: "UTC-05:00" },
//   { name: "Papua New Guinea", code: "PG", timezone: "UTC+10:00" },
//   { name: "Paraguay", code: "PY", timezone: "UTC-04:00" },
//   { name: "Peru", code: "PE", timezone: "UTC-05:00" },
//   { name: "Philippines", code: "PH", timezone: "UTC+08:00" },
//   { name: "Pitcairn", code: "PN", timezone: "UTC-08:00" },
//   { name: "Poland", code: "PL", timezone: "UTC+01:00" },
//   { name: "Portugal", code: "PT", timezone: "UTC+00:00" },
//   { name: "Puerto Rico", code: "PR", timezone: "UTC-04:00" },
//   { name: "Qatar", code: "QA", timezone: "UTC+03:00" },
//   { name: "Reunion", code: "RE", timezone: "UTC+04:00" },
//   { name: "Romania", code: "RO", timezone: "UTC+02:00" },
//   { name: "Russian Federation", code: "RU", timezone: "UTC+03:00" },
//   { name: "RWANDA", code: "RW", timezone: "UTC+02:00" },
//   { name: "Saint Helena", code: "SH", timezone: "UTC+00:00" },
//   { name: "Saint Kitts and Nevis", code: "KN", timezone: "UTC-04:00" },
//   { name: "Saint Lucia", code: "LC", timezone: "UTC-04:00" },
//   { name: "Saint Pierre and Miquelon", code: "PM", timezone: "UTC-03:00" },
//   {
//     name: "Saint Vincent and the Grenadines",
//     code: "VC",
//     timezone: "UTC-04:00",
//   },
//   { name: "Samoa", code: "WS", timezone: "UTC+13:00" },
//   { name: "San Marino", code: "SM", timezone: "UTC+01:00" },
//   { name: "Sao Tome and Principe", code: "ST", timezone: "UTC+00:00" },
//   { name: "Saudi Arabia", code: "SA", timezone: "UTC+03:00" },
//   { name: "Senegal", code: "SN", timezone: "UTC+00:00" },
//   { name: "Serbia", code: "RS", timezone: "UTC+01:00" },
//   { name: "Seychelles", code: "SC", timezone: "UTC+04:00" },
//   { name: "Sierra Leone", code: "SL", timezone: "UTC+00:00" },
//   { name: "Singapore", code: "SG", timezone: "UTC+08:00" },
//   { name: "Slovakia", code: "SK", timezone: "UTC+01:00" },
//   { name: "Slovenia", code: "SI", timezone: "UTC+01:00" },
//   { name: "Solomon Islands", code: "SB", timezone: "UTC+11:00" },
//   { name: "Somalia", code: "SO", timezone: "UTC+03:00" },
//   { name: "South Africa", code: "ZA", timezone: "UTC+02:00" },
//   {
//     name: "South Georgia and the South Sandwich Islands",
//     code: "GS",
//     timezone: "UTC-02:00",
//   },
//   { name: "Spain", code: "ES", timezone: "UTC+01:00" },
//   { name: "Sri Lanka", code: "LK", timezone: "UTC+05:30" },
//   { name: "Sudan", code: "SD", timezone: "UTC+03:00" },
//   { name: "Suriname", code: "SR", timezone: "UTC-03:00" },
//   { name: "Svalbard and Jan Mayen", code: "SJ", timezone: "UTC+01:00" },
//   { name: "Swaziland", code: "SZ", timezone: "UTC+02:00" },
//   { name: "Sweden", code: "SE", timezone: "UTC+01:00" },
//   { name: "Switzerland", code: "CH", timezone: "UTC+01:00" },
//   { name: "Syrian Arab Republic", code: "SY", timezone: "UTC+02:00" },
//   { name: "Taiwan, Province of China", code: "TW", timezone: "UTC+08:00" },
//   { name: "Tajikistan", code: "TJ", timezone: "UTC+05:00" },
//   { name: "Tanzania, United Republic of", code: "TZ", timezone: "UTC+03:00" },
//   { name: "Thailand", code: "TH", timezone: "UTC+07:00" },
//   { name: "Timor-Leste", code: "TL", timezone: "UTC+09:00" },
//   { name: "Togo", code: "TG", timezone: "UTC+00:00" },
//   { name: "Tokelau", code: "TK", timezone: "UTC+13:00" },
//   { name: "Tonga", code: "TO", timezone: "UTC+13:00" },
//   { name: "Trinidad and Tobago", code: "TT", timezone: "UTC-04:00" },
//   { name: "Tunisia", code: "TN", timezone: "UTC+01:00" },
//   { name: "Turkey", code: "TR", timezone: "UTC+03:00" },
//   { name: "Turkmenistan", code: "TM", timezone: "UTC+05:00" },
//   { name: "Turks and Caicos Islands", code: "TC", timezone: "UTC-05:00" },
//   { name: "Tuvalu", code: "TV", timezone: "UTC+12:00" },
//   { name: "Uganda", code: "UG", timezone: "UTC+03:00" },
//   { name: "Ukraine", code: "UA", timezone: "UTC+02:00" },
//   { name: "United Arab Emirates", code: "AE", timezone: "UTC+04:00" },
//   { name: "United Kingdom", code: "GB", timezone: "UTC+00:00" },
//   { name: "United States", code: "US", timezone: "UTC-05:00" },
//   {
//     name: "United States Minor Outlying Islands",
//     code: "UM",
//     timezone: "UTC+12:00",
//   },
//   { name: "Uruguay", code: "UY", timezone: "UTC-03:00" },
//   { name: "Uzbekistan", code: "UZ", timezone: "UTC+05:00" },
//   { name: "Vanuatu", code: "VU", timezone: "UTC+11:00" },
//   { name: "Venezuela", code: "VE", timezone: "UTC-04:00" },
//   { name: "Viet Nam", code: "VN", timezone: "UTC+07:00" },
//   { name: "Virgin Islands, British", code: "VG", timezone: "UTC-04:00" },
//   { name: "Virgin Islands, U.S.", code: "VI", timezone: "UTC-04:00" },
//   { name: "Wallis and Futuna", code: "WF", timezone: "UTC+12:00" },
//   { name: "Western Sahara", code: "EH", timezone: "UTC+00:00" },
//   { name: "Yemen", code: "YE", timezone: "UTC+03:00" },
//   { name: "Zambia", code: "ZM", timezone: "UTC+02:00" },
//   { name: "Zimbabwe", code: "ZW", timezone: "UTC+02:00" },
// ];

// export const countriesOptions = countries.map((country) => ({
//   value: country.code,
//   label: country.name,
// }));

// import moment from "moment-timezone";

// export const countryNameAndCurrentTime = (countryCode) => {
//   const country = countries.find((country) => country.code === countryCode);
//   if (!country) {
//     return { country: "Unknown", currentTime: "N/A" };
//   }

//   const offset = country.timezone;
//   const currentTime = moment
//     .utc()
//     .utcOffset(offset)
//     .format("YYYY-MM-DD HH:mm");

//   return { country: country.name, currentTime };
// };
