export enum tagTypes {
  user = "user",
  service = "service",
  feedback = "feedback",
  appointment = "appointment",
  blog = "blog",
  faq = "faq",
  review = "review",
  news = "news",
  category = "category",
  organization = "organization",
  address = "address",
  event = "event",
  notification = "notification",
  employee = "employee",
  attendance = "attendance",
  leave = "leave",
}

export const tagTypesList = [
  tagTypes.user,
  tagTypes.service,
  tagTypes.feedback,
  tagTypes.appointment,
  tagTypes.blog,
  tagTypes.faq,
  tagTypes.review,
  tagTypes.news,
  tagTypes.category,
  tagTypes.organization,
  tagTypes.address,
  tagTypes.event,
  tagTypes.notification,
  tagTypes.employee,
  tagTypes.attendance,
  tagTypes.leave,
];
